export MONGO_URL := mongodb://localhost:27017/GMNYcustomerDB

start:
	meteor -p 3000

debug:
	NODE_OPTIONS='--debug' meteor -p 3000

android:
	meteor run android

android-device:
	meteor run android-device -p 3000 --verbose